- name: Set Prompt
  ansible.builtin.shell: set-prompt ci-server

- name: Create actions directory
  ansible.builtin.file:
    path: /actions-runner
    state: directory
    owner: ec2-user
    group: ec2-user

- name: Download runner software
  ansible.builtin.unarchive:
    src: https://github.com/actions/runner/releases/download/v2.317.0/actions-runner-linux-x64-2.317.0.tar.gz
    dest: /actions-runner
    owner: ec2-user
    group: ec2-user
    remote_src: true

- name: Install libicu
  ansible.builtin.dnf:
    name: libicu
    state: installed

- name: Remove Runner
  ansible.builtin.shell: /actions-runner/config.sh remove --token {{secrets.runner_token}}
  become_user: ec2-user
  args:
    chdir: /actions-runner

- name: Configure Runner
  ansible.builtin.shell: /actions-runner/config.sh --url https://github.com/raghudevopsb79 --token {{secrets.runner_token}} --unattended
  become_user: ec2-user
  args:
    chdir: /actions-runner

- name: Install Runner Service
  ansible.builtin.shell: ./svc.sh install ;./svc.sh start
  args:
    chdir: /actions-runner

- name: Install java
  ansible.builtin.dnf:
    name: java-17-openjdk
    state: installed

- name: Sonar Directory
  ansible.builtin.file:
    path: /sonar-scanner
    state: directory
    owner: ec2-user
    group: ec2-user

- name: Download and extract sonar-scanner
  ansible.builtin.unarchive:
    remote_src: true
    src: https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-6.1.0.4477-linux-x64.zip
    dest: /sonar-scanner
    owner: ec2-user
    group: ec2-user
