- name: Set Prompt
  ansible.builtin.shell: set-prompt ci-server

- name: Create actions directory
  ansible.builtin.file:
    path: /actions-runner
    state: directory
    owner: ec2-user
    group: ec2-user

- name: Download runner software
  ansible.builtin.unarchive:
    src: https://github.com/actions/runner/releases/download/v2.317.0/actions-runner-linux-x64-2.317.0.tar.gz
    dest: /actions-runner
    owner: ec2-user
    group: ec2-user
    remote_src: true

- name: Configure Runner
  ansible.builtin.shell: /actions-runner/config.sh --url https://github.com/raghudevopsb79 --token {{secrets.runner_token}}
  become_user: ec2-user
  args:
    chdir: /actions-runner


